var lots = [
	{
		"LotCode": "102",
		"LocationCode": "",
		"MaxStayPeriod": "0",
		"BayType": "Disabled",
		"Street": "Franklin Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Franklin",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.319145,
		"Longitude": 149.13231,
		"HasSensor": true
	},
	{
		"LotCode": "201",
		"LocationCode": "",
		"MaxStayPeriod": "0",
		"BayType": "Disabled",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free",
		"PaymentProviderCode": "",
		"BayCount": 2,
		"Latitude": -35.32018,
		"Longitude": 149.131531,
		"HasSensor": true
	},
	{
		"LotCode": "204",
		"LocationCode": "",
		"MaxStayPeriod": "0",
		"BayType": "Disabled",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free",
		"PaymentProviderCode": "",
		"BayCount": 2,
		"Latitude": -35.320823,
		"Longitude": 149.132285,
		"HasSensor": true
	},
	{
		"LotCode": "207",
		"LocationCode": "",
		"MaxStayPeriod": "0",
		"BayType": "Disabled",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.321173,
		"Longitude": 149.133168,
		"HasSensor": true
	},
	{
		"LotCode": "301",
		"LocationCode": "",
		"MaxStayPeriod": "0",
		"BayType": "Disabled",
		"Street": "Furneaux Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Furneaux",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free",
		"PaymentProviderCode": "",
		"BayCount": 2,
		"Latitude": -35.319649,
		"Longitude": 149.131909,
		"HasSensor": true
	},
	{
		"LotCode": "101",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Free",
		"Street": "Franklin Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Franklin",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free_1_hr",
		"PaymentProviderCode": "",
		"BayCount": 19,
		"Latitude": -35.318906,
		"Longitude": 149.132104,
		"HasSensor": true
	},
	{
		"LotCode": "103",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Free",
		"Street": "Franklin Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Franklin",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free_1_hr",
		"PaymentProviderCode": "",
		"BayCount": 6,
		"Latitude": -35.319238,
		"Longitude": 149.132392,
		"HasSensor": true
	},
	{
		"LotCode": "111",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Free",
		"Street": "Franklin Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Franklin",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free_1_hr",
		"PaymentProviderCode": "",
		"BayCount": 6,
		"Latitude": -35.318904,
		"Longitude": 149.131901,
		"HasSensor": true
	},
	{
		"LotCode": "112",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Free",
		"Street": "Franklin Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Franklin",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free_1_hr",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.319236,
		"Longitude": 149.13221,
		"HasSensor": true
	},
	{
		"LotCode": "105",
		"LocationCode": "",
		"MaxStayPeriod": "15",
		"BayType": "15m Free",
		"Street": "Franklin Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Franklin",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free_15_mins",
		"PaymentProviderCode": "",
		"BayCount": 3,
		"Latitude": -35.320348,
		"Longitude": 149.134625,
		"HasSensor": true
	},
	{
		"LotCode": "401",
		"LocationCode": "",
		"MaxStayPeriod": "5",
		"BayType": "Dropoff",
		"Street": "Flinders Way",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Flinders",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free_5_mins",
		"PaymentProviderCode": "",
		"BayCount": 1,
		"Latitude": -35.31999,
		"Longitude": 149.133689,
		"HasSensor": true
	},
	{
		"LotCode": "416",
		"LocationCode": "",
		"MaxStayPeriod": "5",
		"BayType": "5Min Free",
		"Street": "Flinders Way",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Flinders",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free_5_mins",
		"PaymentProviderCode": "",
		"BayCount": 1,
		"Latitude": -35.320933,
		"Longitude": 149.133637,
		"HasSensor": true
	},
	{
		"LotCode": "417",
		"LocationCode": "",
		"MaxStayPeriod": "5",
		"BayType": "5Min Free",
		"Street": "Flinders Way",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Flinders",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "Free_5_mins",
		"PaymentProviderCode": "",
		"BayCount": 3,
		"Latitude": -35.320573,
		"Longitude": 149.13372,
		"HasSensor": true
	},
	{
		"LotCode": "701",
		"LocationCode": "",
		"MaxStayPeriod": "30",
		"BayType": "LZ",
		"Street": "Palmerston Lane",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Palmerston",
		"City": "Manuka",
		"OperatingHourCode": "All_Day",
		"TariffCode": "LZ_&_1P",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.320019,
		"Longitude": 149.132024,
		"HasSensor": true
	},
	{
		"LotCode": "413",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Free",
		"Street": "Flinders Way",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Flinders",
		"City": "Manuka",
		"OperatingHourCode": "Free",
		"TariffCode": "Free_1_hr",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.32175,
		"Longitude": 149.133464,
		"HasSensor": true
	},
	{
		"LotCode": "414",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Free",
		"Street": "Flinders Way",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Flinders",
		"City": "Manuka",
		"OperatingHourCode": "Free",
		"TariffCode": "Free_1_hr",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.321654,
		"Longitude": 149.13349,
		"HasSensor": true
	},
	{
		"LotCode": "415",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Free",
		"Street": "Flinders Way",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Flinders",
		"City": "Manuka",
		"OperatingHourCode": "Free",
		"TariffCode": "Free_1_hr",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.321535,
		"Longitude": 149.133511,
		"HasSensor": true
	},
	{
		"LotCode": "311",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Free",
		"Street": "Furneaux Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Furneaux",
		"City": "Manuka",
		"OperatingHourCode": "Free",
		"TariffCode": "Free_2_hrs",
		"PaymentProviderCode": "",
		"BayCount": 7,
		"Latitude": -35.320252,
		"Longitude": 149.130602,
		"HasSensor": true
	},
	{
		"LotCode": "511",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Free",
		"Street": "Captain Cook Cres",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Captain Cook Cres",
		"City": "Manuka",
		"OperatingHourCode": "Free",
		"TariffCode": "Free_2_hrs",
		"PaymentProviderCode": "",
		"BayCount": 11,
		"Latitude": -35.321474,
		"Longitude": 149.135028,
		"HasSensor": true
	},
	{
		"LotCode": "512",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Free",
		"Street": "Captain Cook Cres",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Captain Cook Cres",
		"City": "Manuka",
		"OperatingHourCode": "Free",
		"TariffCode": "Free_2_hrs",
		"PaymentProviderCode": "",
		"BayCount": 8,
		"Latitude": -35.320302,
		"Longitude": 149.135269,
		"HasSensor": true
	},
	{
		"LotCode": "411",
		"LocationCode": "",
		"MaxStayPeriod": "30",
		"BayType": "30m Free",
		"Street": "Flinders Way",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Flinders",
		"City": "Manuka",
		"OperatingHourCode": "Free",
		"TariffCode": "Free_30_mins",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.321976,
		"Longitude": 149.133417,
		"HasSensor": true
	},
	{
		"LotCode": "412",
		"LocationCode": "",
		"MaxStayPeriod": "30",
		"BayType": "30m Free",
		"Street": "Flinders Way",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Flinders",
		"City": "Manuka",
		"OperatingHourCode": "Free",
		"TariffCode": "Free_30_mins",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.321869,
		"Longitude": 149.133445,
		"HasSensor": true
	},
	{
		"LotCode": "603",
		"LocationCode": "",
		"MaxStayPeriod": "0",
		"BayType": "8P",
		"Street": "Furneaux St Multi Storey - Roof",
		"Zone": "2",
		"SubZone": "2",
		"Ward": "Off Street",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "MS04",
		"PaymentProviderCode": "",
		"BayCount": 82,
		"Latitude": -35.319298,
		"Longitude": 149.130982,
		"HasSensor": true
	},
	{
		"LotCode": "601",
		"LocationCode": "",
		"MaxStayPeriod": "240",
		"BayType": "4P",
		"Street": "Furneaux St Multi Storey - Ground",
		"Zone": "2",
		"SubZone": "2",
		"Ward": "Off Street",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS03",
		"PaymentProviderCode": "",
		"BayCount": 71,
		"Latitude": -35.31942,
		"Longitude": 149.131437,
		"HasSensor": true
	},
	{
		"LotCode": "602",
		"LocationCode": "",
		"MaxStayPeriod": "240",
		"BayType": "4P",
		"Street": "Furneaux St Multi Storey - Level 1",
		"Zone": "2",
		"SubZone": "2",
		"Ward": "Off Street",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS03",
		"PaymentProviderCode": "",
		"BayCount": 38,
		"Latitude": -35.31918,
		"Longitude": 149.131562,
		"HasSensor": true
	},
	{
		"LotCode": "104",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Voucher",
		"Street": "Franklin Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Franklin",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_1P",
		"PaymentProviderCode": "",
		"BayCount": 2,
		"Latitude": -35.320255,
		"Longitude": 149.134267,
		"HasSensor": true
	},
	{
		"LotCode": "113",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Voucher",
		"Street": "Franklin Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Franklin",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_1P",
		"PaymentProviderCode": "",
		"BayCount": 7,
		"Latitude": -35.319806,
		"Longitude": 149.132673,
		"HasSensor": true
	},
	{
		"LotCode": "501",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Voucher",
		"Street": "Captain Cook Cres",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Captain Cook Cres",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_1P",
		"PaymentProviderCode": "",
		"BayCount": 12,
		"Latitude": -35.321103,
		"Longitude": 149.134606,
		"HasSensor": true
	},
	{
		"LotCode": "502",
		"LocationCode": "",
		"MaxStayPeriod": "60",
		"BayType": "1P Voucher",
		"Street": "Captain Cook Cres",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Captain Cook Cres",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_1P",
		"PaymentProviderCode": "",
		"BayCount": 11,
		"Latitude": -35.320821,
		"Longitude": 149.134663,
		"HasSensor": true
	},
	{
		"LotCode": "202",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 8,
		"Latitude": -35.320288,
		"Longitude": 149.131621,
		"HasSensor": true
	},
	{
		"LotCode": "203",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 17,
		"Latitude": -35.320641,
		"Longitude": 149.131988,
		"HasSensor": true
	},
	{
		"LotCode": "205",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 15,
		"Latitude": -35.320956,
		"Longitude": 149.132501,
		"HasSensor": true
	},
	{
		"LotCode": "206",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 9,
		"Latitude": -35.321127,
		"Longitude": 149.132992,
		"HasSensor": true
	},
	{
		"LotCode": "211",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.32024,
		"Longitude": 149.131408,
		"HasSensor": true
	},
	{
		"LotCode": "212",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 7,
		"Latitude": -35.320433,
		"Longitude": 149.131579,
		"HasSensor": true
	},
	{
		"LotCode": "213",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 8,
		"Latitude": -35.32062,
		"Longitude": 149.131796,
		"HasSensor": true
	},
	{
		"LotCode": "214",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 6,
		"Latitude": -35.320792,
		"Longitude": 149.13202,
		"HasSensor": true
	},
	{
		"LotCode": "215",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 7,
		"Latitude": -35.320972,
		"Longitude": 149.132312,
		"HasSensor": true
	},
	{
		"LotCode": "216",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 8,
		"Latitude": -35.321086,
		"Longitude": 149.132579,
		"HasSensor": true
	},
	{
		"LotCode": "217",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 8,
		"Latitude": -35.321189,
		"Longitude": 149.132869,
		"HasSensor": true
	},
	{
		"LotCode": "218",
		"LocationCode": "",
		"MaxStayPeriod": "120",
		"BayType": "2P Voucher",
		"Street": "Bougainville Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Bougainville",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_2P",
		"PaymentProviderCode": "",
		"BayCount": 3,
		"Latitude": -35.321284,
		"Longitude": 149.133197,
		"HasSensor": true
	},
	{
		"LotCode": "302",
		"LocationCode": "",
		"MaxStayPeriod": "30",
		"BayType": "30m Voucher",
		"Street": "Furneaux Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Furneaux",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_30m",
		"PaymentProviderCode": "",
		"BayCount": 11,
		"Latitude": -35.319557,
		"Longitude": 149.132115,
		"HasSensor": true
	},
	{
		"LotCode": "312",
		"LocationCode": "",
		"MaxStayPeriod": "30",
		"BayType": "30m Voucher",
		"Street": "Furneaux Street",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Furneaux",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_30m",
		"PaymentProviderCode": "",
		"BayCount": 3,
		"Latitude": -35.319634,
		"Longitude": 149.132171,
		"HasSensor": true
	},
	{
		"LotCode": "402",
		"LocationCode": "",
		"MaxStayPeriod": "30",
		"BayType": "30m Voucher",
		"Street": "Flinders Way",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Flinders",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_30m",
		"PaymentProviderCode": "",
		"BayCount": 8,
		"Latitude": -35.319879,
		"Longitude": 149.13373,
		"HasSensor": true
	},
	{
		"LotCode": "503",
		"LocationCode": "",
		"MaxStayPeriod": "30",
		"BayType": "30m Voucher",
		"Street": "Captain Cook Cres",
		"Zone": "1",
		"SubZone": "1",
		"Ward": "Captain Cook Cres",
		"City": "Manuka",
		"OperatingHourCode": "Voucher",
		"TariffCode": "SS06_30m",
		"PaymentProviderCode": "",
		"BayCount": 4,
		"Latitude": -35.320141,
		"Longitude": 149.134852,
		"HasSensor": true
	}
];

var lotIndex = {};
for (var i = 0; i < lots.length; i++){
	var lot = lots[i];
	lotIndex[lot.LotCode] = lot;
}